### ISSUE TITLE
Unable to insert only emoji

### ISSUE THREAD

**Issue by Asifkrishaweb** [woody180/vanilla-javascript-emoji-picker#12]
new FgEmojiPicker({
		    trigger: ['button'],
		   	position: ['bottom', 'right'],
		    preFetch: true,
		    emit(obj, triggerElement) {
        		document.querySelector('textarea').value += obj.emoji;
		    }
		});

**Comment by woody180** [comment]
Hi. You must use this plugin with host. Otherwise it won't work!
