### ISSUE TITLE
Display multiple emoji in a contentable at once

### ISSUE THREAD

**Issue by BAALC16** [woody180/vanilla-javascript-emoji-picker#13]
Hi, thanks for your plugin. It’s the only one I found on the net that meets my needs. However I encounter some problems: I created a contentditable that works with the emoji, but each time I click on the "enter" key the emoji that follow the action multiply according to the number "enter".
I wish you could help me. Thanks in advance.

**Comment by RahulChand028** [comment]
@BAALC16  attach any link or document of your code.

**Comment by woody180** [comment]
Fixed in new version
