### ISSUE TITLE
z-index problem with Boostrap 5 Offcanvas

### ISSUE THREAD

**Issue by sti2dSinBastia** [woody180/vanilla-javascript-emoji-picker#14]
Hi, thank you it's a very beautiful emoji picker, but for using it inside a [Bootstrap 5 "Offcanvas" element](https://getbootstrap.com/docs/5.0/components/offcanvas/) you have to increase the z-index from 999 to upper than 1050.

I hope that will help.

**Comment by woody180** [comment]
Fixed in new version
