### ISSUE TITLE
Multiply textarea on same page

### ISSUE THREAD

**Issue by Zimmerlein** [woody180/vanilla-javascript-emoji-picker#15]
Hi Woody180, I love this emoji picker, the only missing feature for me, is the possibility to have multiply emoji pickers on the same page. Is it possible to make the emoji picker uses the nearest textarea from the clicked trigger?

I have tried different methods but couldn't get it to work. Do you know if there is a solution?

**Comment by woody180** [comment]
Hi. there is a new version of the 'emojiPicker' by which you can add multiple pickers on the same page
