### ISSUE TITLE
Disable text selection in Chrome

### ISSUE THREAD

**Issue by limontp** [woody180/vanilla-javascript-emoji-picker#18]
It disables the selection of text in google chrome. 
Firefox working fine though.

**Comment by zonahobby** [comment]
Hello, same problem.

**Comment by limontp** [comment]
Hello
I have fixed it.

**Comment by limontp** [comment]
mouseDown: e => {
            // e.preventDefault();
            moseMove = true;
        },

        mouseUp: e => {
            // e.preventDefault();
            moseMove = false;
        },

        mouseMove: e => {

            let target = e.target;
            while (target && target !== document.body) {
                if (target.classList.contains("fg-emoji-container")){
                    e.preventDefault();
                    break;
                }
                target = target.parentElement;
            }

            if (moseMove) {
                const el = document.querySelector('.fg-emoji-container');
                el.style.left = e.clientX - 320 + 'px';
                el.style.top = e.clientY - 10 + 'px';
            }
        }

Comment out mouseup/mousedown prevent default and then add this in mouse move event

let target = e.target;
            while (target && target !== document.body) {
                if (target.classList.contains("fg-emoji-container")){
                    e.preventDefault();
                    break;
                }
                target = target.parentElement;
            }

**Comment by zonahobby** [comment]
Hello, great! Thanks!! 🤟🤟🤟

**Comment by woody180** [comment]
Hello. I just fixed it

**Comment by limontp** [comment]
Thank you a lot
