### ISSUE TITLE
call on ajax not work

### ISSUE THREAD

**Issue by parsibox** [woody180/vanilla-javascript-emoji-picker#3]
hi
after page load with ajax say error:
FgEmojiPicker is not defined

**Comment by woody180** [comment]
Seems like you didn't import FgEmojiPicker.js file in your page.
Can i see the

**Comment by parsibox** [comment]
![image](https://user-images.githubusercontent.com/12513476/103341140-469cce80-4a9b-11eb-9c1c-88fdcdef5c64.png)

**Comment by parsibox** [comment]
this is my page 
when ajax called it say FgEmojiPicker is not defined

**Comment by woody180** [comment]
There is no reason for you to use timeout function. First of all make sure you load/import fgEmojiPicker.js file properly. Check if 'dir' option loads 'full-emoji-list.json' file from right direction.
And one more thing - i can't understand what are you calling with ajax. If you fetch whole HTML with ajax, than load fgEmojiPicker.js file from the main document

**Comment by parsibox** [comment]
it work with direct url but in ajax it is not work
you can test it
