### ISSUE TITLE
A better way to close the emoji picker ?

### ISSUE THREAD

**Issue by yarekc** [woody180/vanilla-javascript-emoji-picker#5]
The only way to close it seems: 

- ESC keypress
- choose an emoji

There is no "X" close button. Nor the click on blank document closes it.

Any way to add a better way to close it ?

**Comment by woody180** [comment]
There are three actual ways to do that. Two of them you already have mentioned. Third way is to click on the blank screen space.

**Comment by woody180** [comment]
Now you can also use publicly available 'destroy()' method

**Comment by woody180** [comment]
Hey.. Close button is just added.
