### ISSUE TITLE
Please Specify Licence

### ISSUE THREAD

**Issue by annabelle** [woody180/vanilla-javascript-emoji-picker#6]
Hi folks, what licence is this? MIT? BSD? Want to verify if ok to actually use this code for all purposes without issue. Appreciate it.

**Comment by woody180** [comment]
Done. You can use it however you wish

**Comment by annabelle** [comment]
Thank you for the quick response and making the emoji picker available for possible use.

**Comment by marclaporte** [comment]
I see https://github.com/woody180/vanilla-javascript-emoji-picker/commit/6339ae9d013e618b53d56f8c49931f91b557fc41#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7 but this file is no longer in master.

Thanks!

**Comment by woody180** [comment]
Done. LICENSE file is included
