### ISSUE TITLE
Option to keep the emoji picker open after emit an emoji

### ISSUE THREAD

**Issue by Bissel** [woody180/vanilla-javascript-emoji-picker#7]
This is pretty easy to to, just add an option like `removeOnSelection` defaults to true to keep the original behavior. And make an if-statement in the emitEmoji function:
```
if(this.removeOnSelection)
    picker.remove();
```

One of my testers mentioned that most people use multiple emojis and in my opinion it makes sens to have this option if wished.
And thanks a lot for the work on this picker.

**Comment by woody180** [comment]
Thanks. I have recently added to the parameters object.
