### ISSUE TITLE
initialize twice

### ISSUE THREAD

**Issue by ddaniel-gomez** [woody180/vanilla-javascript-emoji-picker#8]
Hello. Thanks for the picker; I like a lot!
I have a question; I'm trying to insert two differents (for 2 different textareas) in the same page but it doesn't work and I've no console errors. 

`const emojiPickerReply = new FgEmojiPicker(opts)`
`const emojiPicker = new FgEmojiPicker(opts)`

Do you know what's going on?

Thanks in advance,

**Comment by woody180** [comment]
Now you can do this with new version
